# Generated by Django 5.1.7 on 2025-03-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
